export const CONVERSION_ERROR_CODES = {
  MISSING_URL: "MISSING_URL",
  INVALID_URL: "INVALID_URL",
  INVALID_PORT: "INVALID_PORT",
  MISSING_DOMAIN: "MISSING_DOMAIN",
  INVALID_PROTOCOL: "INVALID_PROTOCOL",
  MISSING_SECOND_BASE_PATH: "MISSING_SECOND_BASE_PATH",
  WRONG_PROTOCOL: "WRONG_PROTOCOL",
} as const;
